package com.academy.lms.config;
import com.academy.lms.category.*;import com.academy.lms.course.*;import com.academy.lms.enrollment.*;import com.academy.lms.review.*;import com.academy.lms.user.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.*;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.context.annotation.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.support.TransactionTemplate;
@Configuration @ConditionalOnProperty(name="app.seed-enabled",havingValue="true") public class SeedData {
 @Bean ApplicationRunner seed(UserRepository users,RoleRepository roles,CategoryRepository categories,CourseRepository courses,CourseSectionRepository sections,EnrollmentRepository enrollments,ReviewRepository reviews,PasswordEncoder passwords,TransactionTemplate tx,@Value("${app.seed-password}")String seedPassword){return args->tx.executeWithoutResult(s->{if(users.count()>0)return;if(seedPassword==null||seedPassword.length()<12)throw new IllegalStateException("SEED_PASSWORD must contain at least 12 characters when seed data is enabled");
  com.academy.lms.user.Role studentRole=roles.findByName(RoleName.STUDENT).orElseThrow(),instructorRole=roles.findByName(RoleName.INSTRUCTOR).orElseThrow(),adminRole=roles.findByName(RoleName.ADMIN).orElseThrow();String hash=passwords.encode(seedPassword);
  User student=users.save(new User("student@academy.local",hash,"Maya Chen",studentRole));User instructor=users.save(new User("instructor@academy.local",hash,"Dr. Alex Morgan",instructorRole));users.save(new User("admin@academy.local",hash,"Platform Admin",adminRole));
  Category security=categories.save(new Category("Cybersecurity","cybersecurity","Defensive security, risk, and secure engineering"));categories.save(new Category("Cloud Engineering","cloud-engineering","Build resilient modern infrastructure"));categories.save(new Category("Leadership","leadership","Lead teams and shape healthy cultures"));
  Course c=new Course(instructor,security,"Security by Design","security-by-design","Build systems that are resilient from the first commit.","Learn threat modeling, secure architecture, identity boundaries, and pragmatic defense in depth through applied workshops.",Course.Level.INTERMEDIATE,"https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&q=80");c.publish();courses.save(c);
  CourseSection section=new CourseSection(c,"Foundations",0);section.addLesson(new Lesson(section,"Welcome and course map","This course turns security principles into repeatable engineering decisions.",null,0,8,true));section.addLesson(new Lesson(section,"Modeling trust boundaries","Identify assets, entry points, actors, and data flows before choosing controls.",null,1,24,false));sections.save(section);
  enrollments.save(new Enrollment(student,c));Review review=reviews.save(new Review(student,c,(short)5,"Clear, practical, and immediately useful for architecture reviews."));c.updateRating(java.math.BigDecimal.valueOf(5),1);
 });};}
