package com.academy.lms.review;
import com.academy.lms.audit.AuditService;import com.academy.lms.common.exception.ApiException;import com.academy.lms.course.*;import com.academy.lms.enrollment.EnrollmentRepository;import com.academy.lms.user.*;import jakarta.servlet.http.HttpServletRequest;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class ReviewServiceAuthorizationTest {
 @Mock ReviewRepository reviews;@Mock CourseRepository courses;@Mock UserRepository users;@Mock EnrollmentRepository enrollments;@Mock AuditService audit;@Mock HttpServletRequest request;@InjectMocks ReviewService service;
 @Test void nonEnrolledStudentCannotReview(){UUID actor=UUID.randomUUID(),course=UUID.randomUUID();when(enrollments.existsByStudentIdAndCourseId(actor,course)).thenReturn(false);assertEquals(403,assertThrows(ApiException.class,()->service.create(actor,new ReviewDtos.Create(course,(short)5,"Nice"),request)).status().value());verifyNoInteractions(courses);}
 @Test void studentCannotEditAnotherStudentsReview(){UUID actor=UUID.randomUUID();Review review=mock(Review.class);User owner=mock(User.class);when(owner.getId()).thenReturn(UUID.randomUUID());when(review.getStudent()).thenReturn(owner);when(reviews.findById(any())).thenReturn(Optional.of(review));assertEquals(403,assertThrows(ApiException.class,()->service.update(actor,UUID.randomUUID(),new ReviewDtos.Update((short)1,"tamper"),request)).status().value());verify(review,never()).update(anyShort(),anyString());}
 @Test void instructorCannotModerateAnotherInstructorsCourse(){UUID actor=UUID.randomUUID();Review review=mock(Review.class);Course course=mock(Course.class);User owner=mock(User.class);when(owner.getId()).thenReturn(UUID.randomUUID());when(course.getInstructor()).thenReturn(owner);when(review.getCourse()).thenReturn(course);when(reviews.findById(any())).thenReturn(Optional.of(review));assertEquals(403,assertThrows(ApiException.class,()->service.moderate(actor,false,UUID.randomUUID(),new ReviewDtos.Moderate(Review.Status.HIDDEN,"spam"),request)).status().value());verify(review,never()).moderate(any(),any(),any());}
}

