package com.academy.lms.course;
import com.academy.lms.audit.AuditService;import com.academy.lms.category.*;import com.academy.lms.common.exception.ApiException;import com.academy.lms.enrollment.EnrollmentRepository;import com.academy.lms.user.*;import jakarta.persistence.criteria.Predicate;import jakarta.servlet.http.HttpServletRequest;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.security.core.Authentication;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class CourseService {
 private final CourseRepository courses;private final CategoryRepository categories;private final UserRepository users;private final CourseSectionRepository sections;private final EnrollmentRepository enrollments;private final CourseMapper mapper;private final SlugService slugs;private final AuditService audit;
 public CourseService(CourseRepository c,CategoryRepository cat,UserRepository u,CourseSectionRepository s,EnrollmentRepository e,CourseMapper m,SlugService sl,AuditService a){courses=c;categories=cat;users=u;sections=s;enrollments=e;mapper=m;slugs=sl;audit=a;}
 @Transactional(readOnly=true) public Page<CourseDtos.Summary> catalog(String q,UUID category,Course.Level level,int page,int size,String sort){int safe=Math.min(Math.max(size,1),50);Map<String,String> sorts=Map.of("newest","createdAt","title","title","rating","averageRating");String property=sorts.getOrDefault(sort,"createdAt");Sort.Direction dir=sort.equals("title")?Sort.Direction.ASC:Sort.Direction.DESC;Specification<Course> spec=(root,cq,cb)->{List<Predicate> p=new ArrayList<>();p.add(cb.equal(root.get("status"),Course.Status.PUBLISHED));if(q!=null&&!q.isBlank()){String term="%"+q.trim().toLowerCase(Locale.ROOT)+"%";p.add(cb.or(cb.like(cb.lower(root.get("title")),term),cb.like(cb.lower(root.get("shortDescription")),term)));}if(category!=null)p.add(cb.equal(root.get("category").get("id"),category));if(level!=null)p.add(cb.equal(root.get("level"),level));return cb.and(p.toArray(Predicate[]::new));};return courses.findAll(spec,PageRequest.of(Math.max(page,0),safe,Sort.by(dir,property))).map(mapper::summary);}
 @Transactional(readOnly=true) public CourseDtos.Detail get(UUID id,Authentication auth){Course c=find(id);boolean owner=auth!=null&&auth.isAuthenticated()&&currentId(auth).map(c.getInstructor().getId()::equals).orElse(false);boolean admin=has(auth,"ROLE_ADMIN");if(c.getStatus()!=Course.Status.PUBLISHED&&!owner&&!admin)throw ApiException.notFound("Course");boolean enrolled=auth!=null&&auth.isAuthenticated()&&currentId(auth).map(u->enrollments.existsByStudentIdAndCourseId(u,id)).orElse(false);return mapper.detail(c,owner||admin||enrolled);}
 @Transactional public CourseDtos.Detail create(UUID actor,CourseDtos.Upsert r,HttpServletRequest http){User u=users.findById(actor).orElseThrow();Category cat=category(r.categoryId());Course c=courses.save(new Course(u,cat,r.title().trim(),slugs.unique(r.title()),r.shortDescription().trim(),r.description(),r.level(),r.thumbnailUrl()));audit.record(actor,"COURSE_CREATED","COURSE",c.getId(),http.getRemoteAddr());return mapper.detail(c,true);}
 @Transactional public CourseDtos.Detail update(UUID actor,boolean admin,UUID id,CourseDtos.Upsert r,HttpServletRequest http){Course c=managed(actor,admin,id);c.update(category(r.categoryId()),r.title().trim(),c.getTitle().equals(r.title().trim())?c.getSlug():slugs.unique(r.title()),r.shortDescription().trim(),r.description(),r.level(),r.thumbnailUrl());audit.record(actor,"COURSE_UPDATED","COURSE",id,http.getRemoteAddr());return mapper.detail(c,true);}
 @Transactional public CourseDtos.Detail publish(UUID actor,boolean admin,UUID id,HttpServletRequest http){Course c=managed(actor,admin,id);if(c.getSections().isEmpty())throw ApiException.conflict("Add at least one section before publishing");c.publish();audit.record(actor,"COURSE_PUBLISHED","COURSE",id,http.getRemoteAddr());return mapper.detail(c,true);}
 @Transactional public void delete(UUID actor,boolean admin,UUID id,HttpServletRequest http){Course c=managed(actor,admin,id);courses.delete(c);audit.record(actor,"COURSE_DELETED","COURSE",id,http.getRemoteAddr());}
 @Transactional public CourseDtos.Section addSection(UUID actor,boolean admin,UUID id,CourseDtos.CreateSection r){Course c=managed(actor,admin,id);CourseSection s=sections.save(new CourseSection(c,r.title().trim(),r.position()));return new CourseDtos.Section(s.getId(),s.getTitle(),s.getPosition(),List.of());}
 @Transactional public CourseDtos.LessonItem addLesson(UUID actor,boolean admin,UUID sectionId,CourseDtos.CreateLesson r){CourseSection s=sections.findById(sectionId).orElseThrow(()->ApiException.notFound("Section"));if(!admin&&!s.getCourse().getInstructor().getId().equals(actor))throw ApiException.forbidden();Lesson l=new Lesson(s,r.title().trim(),r.content(),r.videoUrl(),r.position(),r.durationMinutes(),r.preview());s.addLesson(l);sections.save(s);return new CourseDtos.LessonItem(l.getId(),l.getTitle(),l.getContent(),l.getVideoUrl(),l.getPosition(),l.getDurationMinutes(),l.isPreview());}
 @Transactional(readOnly=true) public Page<CourseDtos.Summary> managedBy(UUID actor,boolean admin,int page){Specification<Course> s=admin?null:(root,q,cb)->cb.equal(root.get("instructor").get("id"),actor);return courses.findAll(s,PageRequest.of(Math.max(0,page),20,Sort.by(Sort.Direction.DESC,"updatedAt"))).map(mapper::summary);}
 private Course managed(UUID actor,boolean admin,UUID id){Course c=find(id);if(!admin&&!c.getInstructor().getId().equals(actor))throw ApiException.forbidden();return c;}private Course find(UUID id){return courses.findById(id).orElseThrow(()->ApiException.notFound("Course"));}private Category category(UUID id){return id==null?null:categories.findById(id).orElseThrow(()->ApiException.notFound("Category"));}
 private boolean has(Authentication a,String role){return a!=null&&a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals(role));}private Optional<UUID> currentId(Authentication a){return a.getPrincipal() instanceof com.academy.lms.security.AuthenticatedUser u?Optional.of(u.id()):Optional.empty();}
}

