package com.academy.lms.course;
import com.academy.lms.security.CurrentUser;import com.academy.lms.common.api.PageResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.util.UUID;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/courses") public class CourseController {private final CourseService service;public CourseController(CourseService s){service=s;}
 @GetMapping PageResponse<CourseDtos.Summary> list(@RequestParam(required=false)String q,@RequestParam(required=false)UUID category,@RequestParam(required=false)Course.Level level,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="12")int size,@RequestParam(defaultValue="newest")String sort){return PageResponse.from(service.catalog(q,category,level,page,size,sort));}
 @GetMapping("/{id}") CourseDtos.Detail get(@PathVariable UUID id,Authentication a){return service.get(id,a);}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAnyRole('INSTRUCTOR','ADMIN')") CourseDtos.Detail create(@Valid@RequestBody CourseDtos.Upsert r,Authentication a,HttpServletRequest h){return service.create(CurrentUser.id(a),r,h);}
 @PutMapping("/{id}") @PreAuthorize("hasAnyRole('INSTRUCTOR','ADMIN')") CourseDtos.Detail update(@PathVariable UUID id,@Valid@RequestBody CourseDtos.Upsert r,Authentication a,HttpServletRequest h){return service.update(CurrentUser.id(a),isAdmin(a),id,r,h);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAnyRole('INSTRUCTOR','ADMIN')") void delete(@PathVariable UUID id,Authentication a,HttpServletRequest h){service.delete(CurrentUser.id(a),isAdmin(a),id,h);}
 @PostMapping("/{id}/publish") @PreAuthorize("hasAnyRole('INSTRUCTOR','ADMIN')") CourseDtos.Detail publish(@PathVariable UUID id,Authentication a,HttpServletRequest h){return service.publish(CurrentUser.id(a),isAdmin(a),id,h);}
 @PostMapping("/{id}/sections") @PreAuthorize("hasAnyRole('INSTRUCTOR','ADMIN')") CourseDtos.Section section(@PathVariable UUID id,@Valid@RequestBody CourseDtos.CreateSection r,Authentication a){return service.addSection(CurrentUser.id(a),isAdmin(a),id,r);}
 @PostMapping("/sections/{id}/lessons") @PreAuthorize("hasAnyRole('INSTRUCTOR','ADMIN')") CourseDtos.LessonItem lesson(@PathVariable UUID id,@Valid@RequestBody CourseDtos.CreateLesson r,Authentication a){return service.addLesson(CurrentUser.id(a),isAdmin(a),id,r);}
 @GetMapping("/managed") @PreAuthorize("hasAnyRole('INSTRUCTOR','ADMIN')") PageResponse<CourseDtos.Summary> managed(@RequestParam(defaultValue="0")int page,Authentication a){return PageResponse.from(service.managedBy(CurrentUser.id(a),isAdmin(a),page));}
 private boolean isAdmin(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN"));}
}
