package com.academy.lms;
import com.academy.lms.course.CourseRepository;import com.academy.lms.review.ReviewRepository;import com.fasterxml.jackson.databind.ObjectMapper;import jakarta.servlet.http.HttpSession;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.Container;import org.testcontainers.junit.jupiter.Testcontainers;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @Testcontainers class ApiSecurityIntegrationTest {
 @Container static PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:16-alpine").withDatabaseName("lms_test").withUsername("lms").withPassword("lms");
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);r.add("app.seed-enabled",()->"true");r.add("app.seed-password",()->"LearnSecure123!");}
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired CourseRepository courses;@Autowired ReviewRepository reviews;
 @Test void unauthenticatedMutationIsRejected()throws Exception{mvc.perform(post("/api/courses").with(csrf()).contentType("application/json").content("{}" )).andExpect(status().isUnauthorized());}
 @Test void studentCannotAccessAdminOrCreateCourse()throws Exception{HttpSession s=login("student@academy.local","LearnSecure123!");mvc.perform(get("/api/dashboard/admin").session((org.springframework.mock.web.MockHttpSession)s)).andExpect(status().isForbidden());String valid="{\"title\":\"Unauthorized course\",\"shortDescription\":\"A valid description\",\"description\":\"A valid long description\",\"level\":\"BEGINNER\"}";mvc.perform(post("/api/courses").session((org.springframework.mock.web.MockHttpSession)s).with(csrf()).contentType("application/json").content(valid)).andExpect(status().isForbidden());}
 @Test void registrationIgnoresSpoofedAdminRole()throws Exception{String body="{\"email\":\"attacker@example.test\",\"password\":\"A-very-secure-password1!\",\"displayName\":\"Attacker\",\"roles\":[\"ADMIN\"]}";MvcResult result=mvc.perform(post("/api/auth/register").with(csrf()).contentType("application/json").content(body)).andExpect(status().isCreated()).andExpect(jsonPath("$.user.roles[0]").value("STUDENT")).andReturn();mvc.perform(get("/api/dashboard/admin").session((org.springframework.mock.web.MockHttpSession)result.getRequest().getSession())).andExpect(status().isForbidden());}
 @Test void nonEnrolledIdentitySpoofCannotCreateReview()throws Exception{String email="outsider@example.test";MvcResult result=mvc.perform(post("/api/auth/register").with(csrf()).contentType("application/json").content("{\"email\":\""+email+"\",\"password\":\"A-very-secure-password1!\",\"displayName\":\"Outsider\"}")).andExpect(status().isCreated()).andReturn();String courseId=courses.findAll().getFirst().getId().toString();String seededStudentId=reviews.findAll().getFirst().getStudent().getId().toString();mvc.perform(post("/api/reviews").session((org.springframework.mock.web.MockHttpSession)result.getRequest().getSession()).with(csrf()).contentType("application/json").content("{\"courseId\":\""+courseId+"\",\"rating\":5,\"comment\":\"spoof\",\"studentId\":\""+seededStudentId+"\"}")).andExpect(status().isForbidden());}
 @Test void csrfIsRequiredForAuthenticatedMutation()throws Exception{HttpSession s=login("student@academy.local","LearnSecure123!");mvc.perform(post("/api/courses/"+courses.findAll().getFirst().getId()+"/enroll").session((org.springframework.mock.web.MockHttpSession)s)).andExpect(status().isForbidden());}
 @Test void duplicateReviewIsRejected()throws Exception{HttpSession s=login("student@academy.local","LearnSecure123!");String courseId=courses.findAll().getFirst().getId().toString();mvc.perform(post("/api/reviews").session((org.springframework.mock.web.MockHttpSession)s).with(csrf()).contentType("application/json").content("{\"courseId\":\""+courseId+"\",\"rating\":4,\"comment\":\"duplicate\"}")).andExpect(status().isConflict());}
 @Test void sqlInjectionShapedSearchIsHandledAsData()throws Exception{mvc.perform(get("/api/courses").param("q","' OR 1=1 --")).andExpect(status().isOk()).andExpect(jsonPath("$.content").isArray());}
 private HttpSession login(String email,String password)throws Exception{return mvc.perform(post("/api/auth/login").with(csrf()).contentType("application/json").content("{\"email\":\""+email+"\",\"password\":\""+password+"\"}")).andExpect(status().isOk()).andReturn().getRequest().getSession();}
}
