package com.academy.lms.review;
import com.academy.lms.audit.AuditService;import com.academy.lms.common.exception.ApiException;import com.academy.lms.course.*;import com.academy.lms.enrollment.EnrollmentRepository;import com.academy.lms.user.*;import jakarta.servlet.http.HttpServletRequest;import java.math.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class ReviewService {private final ReviewRepository reviews;private final CourseRepository courses;private final UserRepository users;private final EnrollmentRepository enrollments;private final AuditService audit;public ReviewService(ReviewRepository r,CourseRepository c,UserRepository u,EnrollmentRepository e,AuditService a){reviews=r;courses=c;users=u;enrollments=e;audit=a;}
 @Transactional public ReviewDtos.View create(UUID actor,ReviewDtos.Create r,HttpServletRequest h){if(!enrollments.existsByStudentIdAndCourseId(actor,r.courseId()))throw ApiException.forbidden();if(reviews.existsByStudentIdAndCourseId(actor,r.courseId()))throw ApiException.conflict("You have already reviewed this course");Course c=courses.findById(r.courseId()).orElseThrow(()->ApiException.notFound("Course"));User u=users.findById(actor).orElseThrow();Review v=reviews.save(new Review(u,c,r.rating(),r.comment().trim()));recalculate(c);audit.record(actor,"REVIEW_CREATED","REVIEW",v.getId(),h.getRemoteAddr());return dto(v);}
 @Transactional(readOnly=true) public Page<ReviewDtos.View> list(UUID course,int page,int size){return reviews.findByCourseIdAndStatus(course,Review.Status.PUBLISHED,PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),50),Sort.by(Sort.Direction.DESC,"createdAt"))).map(this::dto);}
 @Transactional public ReviewDtos.View update(UUID actor,UUID id,ReviewDtos.Update r,HttpServletRequest h){Review v=find(id);if(!v.getStudent().getId().equals(actor))throw ApiException.forbidden();v.update(r.rating(),r.comment().trim());recalculate(v.getCourse());audit.record(actor,"REVIEW_UPDATED","REVIEW",id,h.getRemoteAddr());return dto(v);}
 @Transactional public void delete(UUID actor,boolean admin,UUID id,HttpServletRequest h){Review v=find(id);if(!admin&&!v.getStudent().getId().equals(actor))throw ApiException.forbidden();Course c=v.getCourse();reviews.delete(v);reviews.flush();recalculate(c);audit.record(actor,"REVIEW_DELETED","REVIEW",id,h.getRemoteAddr());}
 @Transactional public ReviewDtos.View moderate(UUID actor,boolean admin,UUID id,ReviewDtos.Moderate r,HttpServletRequest h){Review v=find(id);if(!admin&&!v.getCourse().getInstructor().getId().equals(actor))throw ApiException.forbidden();if(r.status()==Review.Status.HIDDEN&&(r.reason()==null||r.reason().isBlank()))throw new ApiException(org.springframework.http.HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","A reason is required when hiding a review");v.moderate(r.status(),r.reason(),users.findById(actor).orElseThrow());recalculate(v.getCourse());audit.record(actor,"REVIEW_MODERATED","REVIEW",id,h.getRemoteAddr());return dto(v);}
 private void recalculate(Course c){reviews.flush();Object[] a=reviews.aggregate(c.getId());Number avg=a!=null&&a.length>0&&a[0]!=null?(Number)a[0]:BigDecimal.ZERO;Number count=a!=null&&a.length>1&&a[1]!=null?(Number)a[1]:0;c.updateRating(BigDecimal.valueOf(avg.doubleValue()).setScale(2,RoundingMode.HALF_UP),count.intValue());}
 private Review find(UUID id){return reviews.findById(id).orElseThrow(()->ApiException.notFound("Review"));}private ReviewDtos.View dto(Review r){return new ReviewDtos.View(r.getId(),r.getCourse().getId(),r.getStudent().getId(),r.getStudent().getDisplayName(),r.getRating(),r.getComment(),r.getStatus(),r.getModerationReason(),r.getCreatedAt(),r.getUpdatedAt());}
}

